import type { FormatSpec, RouteSpec } from "@/lib/types";

export const formats: Record<string, FormatSpec> = {
  pt: {
    id: "pt",
    name: "PyTorch Weights",
    suffixes: [".pt"],
    category: "source",
    canBeSource: true,
    canBeTarget: false,
    oneWay: false,
    platformLocked: false,
    notes: "Ultralytics YOLO .pt files only. Generic PyTorch checkpoints are not supported.",
  },
  torchscript: {
    id: "torchscript",
    name: "TorchScript",
    suffixes: [".torchscript"],
    category: "intermediate",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
    notes: "Traced TorchScript module. Easiest target after ONNX.",
  },
  onnx: {
    id: "onnx",
    name: "ONNX",
    suffixes: [".onnx"],
    category: "intermediate",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
    notes: "Most portable intermediate. Planned source format for selected downstream routes.",
  },
  openvino: {
    id: "openvino",
    name: "OpenVINO IR",
    suffixes: ["_openvino_model/"],
    category: "intermediate",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
    notes: "Optimised for Intel CPUs, iGPUs, and VPUs.",
  },
  engine: {
    id: "engine",
    name: "TensorRT Engine",
    suffixes: [".engine"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: true,
    notes: "GPU architecture and TensorRT version locked.",
  },
  coreml: {
    id: "coreml",
    name: "CoreML",
    suffixes: [".mlpackage"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: true,
    notes: "Apple ecosystem only. Cannot be built on Windows.",
  },
  saved_model: {
    id: "saved_model",
    name: "TF SavedModel",
    suffixes: ["_saved_model/"],
    category: "intermediate",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
  },
  tflite: {
    id: "tflite",
    name: "TFLite",
    suffixes: [".tflite"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: false,
    notes: "TensorFlow Lite flatbuffer. INT8 variant requires calibration data.",
  },
  edgetpu: {
    id: "edgetpu",
    name: "Edge TPU",
    suffixes: ["_edgetpu.tflite"],
    category: "vendor",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: true,
    notes: "Google Coral hardware only. Linux x86_64 export only.",
  },
  tfjs: {
    id: "tfjs",
    name: "TensorFlow.js",
    suffixes: ["_web_model/"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
  },
  paddle: {
    id: "paddle",
    name: "PaddlePaddle",
    suffixes: ["_paddle_model/"],
    category: "intermediate",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
  },
  ncnn: {
    id: "ncnn",
    name: "NCNN",
    suffixes: ["_ncnn_model/"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
  },
  mnn: {
    id: "mnn",
    name: "MNN",
    suffixes: [".mnn"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: false,
  },
  rknn: {
    id: "rknn",
    name: "RKNN",
    suffixes: ["_rknn_model/"],
    category: "vendor",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: false,
    notes: "Rockchip NPU binary. Target chip must be specified.",
  },
  imx: {
    id: "imx",
    name: "Sony IMX500",
    suffixes: ["_imx_model/"],
    category: "vendor",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: true,
  },
  executorch: {
    id: "executorch",
    name: "ExecuTorch",
    suffixes: [".pte"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: false,
  },
  axelera: {
    id: "axelera",
    name: "Axelera Metis",
    suffixes: ["_axelera_model/"],
    category: "vendor",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: true,
  },
};

const route = (spec: Omit<RouteSpec, "providerId" | "sourceFormat" | "sysDeps" | "platformLock" | "intermediates" | "requiresGpu" | "supportsHalf" | "supportsInt8" | "supportsDynamic" | "needsCalibration" | "oneWay" | "lossy"> & Partial<RouteSpec>): RouteSpec => ({
  providerId: "ultralytics",
  sourceFormat: "pt",
  sysDeps: [],
  platformLock: "any",
  intermediates: [],
  requiresGpu: false,
  supportsHalf: false,
  supportsInt8: false,
  supportsDynamic: false,
  needsCalibration: false,
  oneWay: false,
  lossy: false,
  ...spec,
});

export const ultralyticsRoutes: RouteSpec[] = [
  route({
    id: "ultralytics.pt.torchscript",
    targetFormat: "torchscript",
    title: "TorchScript",
    displayPath: "model.pt → model.torchscript",
    pipDeps: [],
    supportsHalf: true,
    supportsDynamic: true,
    notes: "Uses torch.jit.trace with strict=False.",
  }),
  route({
    id: "ultralytics.pt.onnx",
    targetFormat: "onnx",
    title: "ONNX",
    displayPath: "model.pt → model.onnx",
    pipDeps: [
      { packageName: "onnx", installHint: "pip install onnx" },
      { packageName: "onnxslim", installHint: "pip install onnxslim" },
    ],
    supportsHalf: true,
    supportsDynamic: true,
    notes: "Most portable format. onnxslim optional.",
  }),
  route({
    id: "ultralytics.pt.openvino",
    targetFormat: "openvino",
    title: "OpenVINO",
    displayPath: "model.pt → model_openvino_model/",
    pipDeps: [
      { packageName: "openvino", installHint: "pip install openvino" },
      { packageName: "nncf", installHint: "pip install nncf" },
    ],
    supportsHalf: true,
    supportsInt8: true,
    supportsDynamic: true,
    needsCalibration: true,
    calibrationMode: "when_int8",
    notes: "Direct PyTorch → OpenVINO IR. INT8 requires nncf + calibration data.",
  }),
  route({
    id: "ultralytics.pt.coreml",
    targetFormat: "coreml",
    title: "CoreML",
    displayPath: "model.pt → model.torchscript → model.mlpackage",
    pipDeps: [{ packageName: "coremltools", installHint: "pip install coremltools" }],
    platformLock: "not_windows",
    intermediates: ["torchscript"],
    supportsHalf: true,
    supportsInt8: true,
    oneWay: true,
    lossy: true,
    notes: "macOS/Linux only. Intermediate TorchScript is discarded. One-way.",
  }),
  route({
    id: "ultralytics.pt.ncnn",
    targetFormat: "ncnn",
    title: "NCNN",
    displayPath: "model.pt → model_ncnn_model/",
    pipDeps: [
      { packageName: "ncnn", installHint: "pip install ncnn" },
      { packageName: "pnnx", installHint: "pip install pnnx" },
    ],
    supportsHalf: true,
    notes: "Lightweight mobile/embedded inference. Requires ncnn and pnnx.",
  }),
  route({
    id: "ultralytics.pt.mnn",
    targetFormat: "mnn",
    title: "MNN",
    displayPath: "model.pt → model.onnx → model.mnn",
    pipDeps: [
      { packageName: "MNN", installHint: "pip install MNN" },
      { packageName: "onnx", installHint: "pip install onnx" },
    ],
    intermediates: ["onnx"],
    supportsHalf: true,
    supportsInt8: true,
    oneWay: true,
    notes: "MNN mobile inference. Intermediate ONNX is discarded. One-way.",
  }),
  route({
    id: "ultralytics.pt.tflite",
    targetFormat: "tflite",
    title: "TFLite",
    displayPath: "model.pt → model.onnx → saved_model/ → model.tflite",
    pipDeps: [
      { packageName: "tensorflow", installHint: "pip install tensorflow" },
      { packageName: "onnx2tf", installHint: "pip install onnx2tf" },
      { packageName: "onnx", installHint: "pip install onnx" },
      { packageName: "onnxruntime", installHint: "pip install onnxruntime" },
    ],
    intermediates: ["onnx", "saved_model"],
    supportsHalf: true,
    supportsInt8: true,
    oneWay: true,
    lossy: true,
    needsCalibration: true,
    calibrationMode: "when_int8",
    notes: "EdgeTPU / mobile deployment. Multi-step pipeline. One-way, lossy. INT8 requires calibration data.",
  }),
  route({
    id: "ultralytics.pt.engine",
    targetFormat: "engine",
    title: "TensorRT",
    displayPath: "model.pt → model.onnx → model.engine",
    pipDeps: [{ packageName: "tensorrt", installHint: "pip install tensorrt" }],
    intermediates: ["onnx"],
    requiresGpu: true,
    supportsHalf: true,
    supportsInt8: true,
    oneWay: true,
    lossy: true,
    needsCalibration: true,
    calibrationMode: "when_int8",
    notes: "TensorRT engine. NVIDIA GPU required. One-way, platform-locked at runtime. INT8 requires calibration dataset.",
  }),
  route({
    id: "ultralytics.pt.rknn",
    targetFormat: "rknn",
    title: "RKNN",
    displayPath: "model.pt → _rknn_model/{stem}-{chip}.rknn",
    pipDeps: [
      { packageName: "rknn-toolkit2", installHint: "pip install rknn-toolkit2" },
      { packageName: "onnx", installHint: "pip install onnx" },
    ],
    intermediates: ["onnx"],
    oneWay: true,
    lossy: true,
    notes: "Rockchip NPU deployment. Requires target chip name (name= option). Lossy: discards FP precision.",
  }),
  route({
    id: "ultralytics.pt.executorch",
    targetFormat: "executorch",
    title: "ExecuTorch",
    displayPath: "model.pt → model.pte",
    pipDeps: [{ packageName: "executorch", installHint: "pip install executorch" }],
    oneWay: true,
    notes: "PyTorch ExecuTorch on-device inference. Requires torch >= 2.9. One-way.",
  }),
  route({
    id: "ultralytics.pt.edgetpu",
    targetFormat: "edgetpu",
    title: "Edge TPU",
    displayPath: "model.pt → model.onnx → saved_model/ → model.tflite → edgetpu_compiler → model_edgetpu.tflite",
    pipDeps: [
      { packageName: "tensorflow", installHint: "pip install tensorflow" },
      { packageName: "onnx2tf", installHint: "pip install onnx2tf" },
      { packageName: "onnx", installHint: "pip install onnx" },
      { packageName: "onnxruntime", installHint: "pip install onnxruntime" },
    ],
    sysDeps: [{ binaryName: "edgetpu_compiler", installHint: "Download from https://coral.ai/docs/edgetpu/compiler/#download" }],
    platformLock: "linux_x86_64",
    intermediates: ["onnx", "saved_model", "tflite"],
    oneWay: true,
    lossy: true,
    needsCalibration: true,
    calibrationMode: "always",
    notes: "Google Coral hardware only. Full-integer quantisation forced. Linux x86_64 and edgetpu_compiler binary required.",
  }),
  route({
    id: "ultralytics.pt.tfjs",
    targetFormat: "tfjs",
    title: "TF.js",
    displayPath: "model.pt → model.onnx → saved_model/ → model.pb → tensorflowjs_converter → model_web_model/",
    pipDeps: [
      { packageName: "tensorflow", installHint: "pip install tensorflow" },
      { packageName: "onnx2tf", installHint: "pip install onnx2tf" },
      { packageName: "onnx", installHint: "pip install onnx" },
      { packageName: "onnxruntime", installHint: "pip install onnxruntime" },
      { packageName: "tensorflowjs", installHint: "pip install tensorflowjs" },
    ],
    sysDeps: [{ binaryName: "tensorflowjs_converter", installHint: "pip install tensorflowjs" }],
    intermediates: ["onnx", "saved_model", "pb"],
    supportsHalf: true,
    supportsInt8: true,
    needsCalibration: true,
    calibrationMode: "when_int8",
    notes: "Browser/Node.js deployment. tensorflowjs_converter binary installed via pip install tensorflowjs. INT8 requires calibration data.",
  }),
  route({
    id: "ultralytics.pt.paddle",
    targetFormat: "paddle",
    title: "PaddlePaddle",
    displayPath: "model.pt → model_paddle_model/",
    pipDeps: [
      { packageName: "paddlepaddle", installHint: "pip install paddlepaddle" },
      { packageName: "x2paddle", installHint: "pip install x2paddle" },
    ],
    notes: "PaddlePaddle via x2paddle jit.trace. Direct PyTorch → Paddle.",
  }),
  route({
    id: "ultralytics.pt.imx",
    targetFormat: "imx",
    title: "Sony IMX500",
    displayPath: "model.pt → FXModel → MCT INT8 → model_imx.onnx → imxconv-pt → model_imx_model/",
    pipDeps: [
      { packageName: "model-compression-toolkit", installHint: "pip install model-compression-toolkit" },
      { packageName: "sony-custom-layers", installHint: "pip install sony-custom-layers" },
      { packageName: "imx500-converter", installHint: "pip install imx500-converter" },
    ],
    sysDeps: [
      { binaryName: "imxconv-pt", installHint: "pip install imx500-converter" },
      { binaryName: "java", installHint: "Install Java >= 17: https://adoptium.net/" },
    ],
    platformLock: "linux",
    intermediates: ["onnx"],
    supportsInt8: true,
    oneWay: true,
    lossy: true,
    needsCalibration: true,
    calibrationMode: "always",
    notes: "Sony IMX500 AI sensor. Linux only. int8 forced True. Java >= 17 required. Calibration always required.",
  }),
  route({
    id: "ultralytics.pt.axelera",
    targetFormat: "axelera",
    title: "Axelera",
    displayPath: "model.pt → axelera.quantize → axelera.compile → model_axelera_model/",
    pipDeps: [{ packageName: "axelera", installHint: "pip install axelera-devkit" }],
    platformLock: "linux",
    supportsInt8: true,
    oneWay: true,
    lossy: true,
    needsCalibration: true,
    calibrationMode: "always",
    notes: "Axelera Metis AIPU binary. Linux only. Calibration required. Requires torch >= 2.8.",
  }),
];

export const defaultRoute = ultralyticsRoutes.find((item) => item.targetFormat === "onnx") ?? ultralyticsRoutes[0];
