import type { FormatSpec } from "@/lib/types";
import { defaultRouteForProvider } from "@/lib/providers";

export const formats: Record<string, FormatSpec> = {
  pt: {
    id: "pt",
    name: "PyTorch Weights",
    suffixes: [".pt"],
    category: "source",
    canBeSource: true,
    canBeTarget: false,
    oneWay: false,
    platformLocked: false,
    notes: "Ultralytics YOLO .pt files only. Generic PyTorch checkpoints are not supported.",
  },
  pth: {
    id: "pth",
    name: "RF-DETR Checkpoint",
    suffixes: [".pth"],
    category: "source",
    canBeSource: true,
    canBeTarget: false,
    oneWay: false,
    platformLocked: false,
    notes: "Roboflow RF-DETR .pth checkpoints only. Generic PyTorch checkpoints are not supported.",
  },
  torchscript: {
    id: "torchscript",
    name: "TorchScript",
    suffixes: [".torchscript"],
    category: "intermediate",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
    notes: "Traced TorchScript module. Easiest target after ONNX.",
  },
  onnx: {
    id: "onnx",
    name: "ONNX",
    suffixes: [".onnx"],
    category: "intermediate",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
    notes: "Most portable intermediate. Planned source format for selected downstream routes.",
  },
  openvino: {
    id: "openvino",
    name: "OpenVINO IR",
    suffixes: ["_openvino_model/"],
    category: "intermediate",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
    notes: "Optimised for Intel CPUs, iGPUs, and VPUs.",
  },
  engine: {
    id: "engine",
    name: "TensorRT Engine",
    suffixes: [".engine"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: true,
    notes: "GPU architecture and TensorRT version locked.",
  },
  coreml: {
    id: "coreml",
    name: "CoreML",
    suffixes: [".mlpackage"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: true,
    notes: "Apple ecosystem only. Cannot be built on Windows.",
  },
  saved_model: {
    id: "saved_model",
    name: "TF SavedModel",
    suffixes: ["_saved_model/"],
    category: "intermediate",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
    notes: "TensorFlow Serving and cloud deployment.",
  },
  pb: {
    id: "pb",
    name: "TF GraphDef",
    suffixes: [".pb"],
    category: "intermediate",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
    notes: "TensorFlow frozen graph inference.",
  },
  tflite: {
    id: "tflite",
    name: "TFLite",
    suffixes: [".tflite"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: false,
    notes: "TensorFlow Lite flatbuffer.",
  },
  edgetpu: {
    id: "edgetpu",
    name: "TF Edge TPU",
    suffixes: ["_edgetpu.tflite"],
    category: "vendor",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: true,
    notes: "Google Coral hardware only. Linux x86_64 export only.",
  },
  tfjs: {
    id: "tfjs",
    name: "TensorFlow.js",
    suffixes: ["_web_model/"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
  },
  paddle: {
    id: "paddle",
    name: "PaddlePaddle",
    suffixes: ["_paddle_model/"],
    category: "intermediate",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
  },
  ncnn: {
    id: "ncnn",
    name: "NCNN",
    suffixes: ["_ncnn_model/"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: false,
    platformLocked: false,
  },
  mnn: {
    id: "mnn",
    name: "MNN",
    suffixes: [".mnn"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: false,
  },
  rknn: {
    id: "rknn",
    name: "RKNN",
    suffixes: ["_rknn_model/"],
    category: "vendor",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: false,
    notes: "Rockchip NPU binary. Target chip must be specified.",
  },
  imx: {
    id: "imx",
    name: "Sony IMX500",
    suffixes: ["_imx_model/"],
    category: "vendor",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: true,
  },
  executorch: {
    id: "executorch",
    name: "ExecuTorch",
    suffixes: [".pte"],
    category: "runtime",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: false,
  },
  axelera: {
    id: "axelera",
    name: "Axelera Metis",
    suffixes: ["_axelera_model/"],
    category: "vendor",
    canBeSource: false,
    canBeTarget: true,
    oneWay: true,
    platformLocked: true,
  },
};

export {
  defaultRouteForProvider,
  findRoute,
  hasAllowedSourceExtension,
  providerList,
  providers,
  rfdetrRoutes,
  routesByProvider,
  routesForProvider,
  ultralyticsRoutes,
} from "@/lib/providers";

export const defaultRoute = defaultRouteForProvider("ultralytics");
