import type { ProviderSpec, RouteSpec } from "@/lib/types";

export const rfdetrProvider: ProviderSpec = {
  id: "rfdetr",
  displayName: "Roboflow RF-DETR",
  shortName: "RF-DETR",
  sourceFormat: "pth",
  sourceExtensions: [".pth"],
  pickerFilterName: "RF-DETR Checkpoint",
  dropTitle: "Drop .pth checkpoint",
  dropHelper: "Local Roboflow RF-DETR export using the selected Python environment.",
  baseDeps: [],
};

const rfdetrRoute = (spec: Omit<RouteSpec, "providerId" | "sourceFormat" | "sysDeps" | "platformLock" | "intermediates" | "requiresGpu" | "precisionModes" | "defaultPrecision" | "calibrationRecommendedFor" | "supportsDynamic" | "oneWay" | "lossy"> & Partial<RouteSpec>): RouteSpec => ({
  providerId: "rfdetr",
  sourceFormat: "pth",
  sysDeps: [],
  platformLock: "any",
  intermediates: [],
  requiresGpu: false,
  precisionModes: ["fp32"],
  defaultPrecision: "fp32",
  calibrationRecommendedFor: [],
  supportsDynamic: false,
  oneWay: false,
  lossy: false,
  ...spec,
});

export const rfdetrRoutes: RouteSpec[] = [
  rfdetrRoute({
    id: "rfdetr.pth.onnx",
    targetFormat: "onnx",
    title: "ONNX",
    displayPath: "checkpoint.pth -> inference_model.onnx",
    pipDeps: [{ packageName: "rfdetr[onnx]", installHint: 'pip install "rfdetr[onnx]"' }],
    notes: "Recommended RF-DETR export target and primary validation path.",
  }),
  rfdetrRoute({
    id: "rfdetr.pth.engine",
    targetFormat: "engine",
    title: "TensorRT via ONNX",
    displayPath: "checkpoint.pth -> model.trt",
    pipDeps: [{ packageName: "rfdetr[tensorrt]", installHint: 'pip install "rfdetr[tensorrt]"' }],
    platformLock: "linux_windows",
    intermediates: ["onnx"],
    requiresGpu: true,
    oneWay: true,
    lossy: true,
    notes: "Uses RF-DETR's native TensorRT export for NVIDIA deployment hardware.",
    unsupportedNote: "TensorRT requires an NVIDIA GPU. NVIDIA does not support macOS.",
  }),
  rfdetrRoute({
    id: "rfdetr.pth.coreml",
    targetFormat: "coreml",
    title: "CoreML",
    displayPath: "checkpoint.pth -> rfdetr-small.mlpackage",
    pipDeps: [{ packageName: "rfdetr[coreml]", installHint: 'pip install "rfdetr[coreml]"' }],
    platformLock: "macos",
    precisionModes: ["fp32", "fp16"],
    defaultPrecision: "fp32",
    oneWay: true,
    lossy: true,
    notes: "Experimental native CoreML export. Fixed shapes only; dynamic batch is unsupported.",
    unsupportedNote: "CoreML export requires macOS.",
  }),
  rfdetrRoute({
    id: "rfdetr.pth.tflite",
    targetFormat: "tflite",
    title: "TFLite",
    displayPath: "checkpoint.pth -> multiple .tflite files",
    pipDeps: [{ packageName: "rfdetr[tflite]", installHint: 'pip install "rfdetr[tflite]"' }],
    intermediates: ["onnx"],
    precisionModes: ["fp32", "fp16", "int8"],
    defaultPrecision: "fp32",
    calibrationRecommendedFor: ["int8"],
    oneWay: true,
    lossy: true,
    experimental: true,
    notes: "Experimental ONNX → TensorFlow → TFLite export; onnx2tf output layouts can vary. Export always produces FP32 and FP16 files; INT8 adds a third file.",
  }),
];
