import type { ProviderSpec, RouteSpec } from "@/lib/types";

export const ultralyticsProvider: ProviderSpec = {
  id: "ultralytics",
  displayName: "Ultralytics YOLO",
  shortName: "YOLO",
  sourceFormat: "pt",
  sourceExtensions: [".pt"],
  pickerFilterName: "Ultralytics YOLO Weights",
  dropTitle: "Drop .pt model",
  dropHelper: "Local Ultralytics export using the selected Python environment.",
  baseDeps: [{ packageName: "ultralytics", installHint: "pip install ultralytics" }],
};

const route = (spec: Omit<RouteSpec, "providerId" | "sourceFormat" | "sysDeps" | "platformLock" | "intermediates" | "requiresGpu" | "precisionModes" | "defaultPrecision" | "calibrationRecommendedFor" | "supportsDynamic" | "oneWay" | "lossy"> & Partial<RouteSpec>): RouteSpec => ({
  providerId: "ultralytics",
  sourceFormat: "pt",
  sysDeps: [],
  platformLock: "any",
  intermediates: [],
  requiresGpu: false,
  precisionModes: ["fp32"],
  defaultPrecision: "fp32",
  calibrationRecommendedFor: [],
  supportsDynamic: false,
  oneWay: false,
  lossy: false,
  ...spec,
});

export const ultralyticsRoutes: RouteSpec[] = [
  route({
    id: "ultralytics.pt.onnx",
    targetFormat: "onnx",
    title: "ONNX",
    displayPath: "model.pt → model.onnx",
    pipDeps: [
      { packageName: "onnx", installHint: "pip install onnx" },
      { packageName: "onnxslim", installHint: "pip install onnxslim", optional: true },
    ],
    precisionModes: ["fp16", "fp32", "int8"],
    defaultPrecision: "fp16",
    calibrationRecommendedFor: ["int8"],
    supportsDynamic: true,
    notes: "Most portable format. onnxslim optional.",
  }),
  route({
    id: "ultralytics.pt.torchscript",
    targetFormat: "torchscript",
    title: "TorchScript",
    displayPath: "model.pt → model.torchscript",
    pipDeps: [],
    supportsDynamic: true,
    notes: "Uses torch.jit.trace with strict=False.",
  }),
  route({
    id: "ultralytics.pt.openvino",
    targetFormat: "openvino",
    title: "OpenVINO",
    displayPath: "model.pt → model_openvino_model/",
    pipDeps: [
      { packageName: "openvino", installHint: "pip install openvino" },
      { packageName: "nncf", installHint: "pip install nncf" },
    ],
    precisionModes: ["fp16", "fp32", "int8"],
    defaultPrecision: "fp16",
    calibrationRecommendedFor: ["int8"],
    supportsDynamic: true,
    notes: "Direct PyTorch → OpenVINO IR. INT8 via NNCF.",
  }),
  route({
    id: "ultralytics.pt.engine",
    targetFormat: "engine",
    title: "TensorRT",
    displayPath: "model.pt → model.onnx → model.engine",
    pipDeps: [{ packageName: "tensorrt", installHint: "pip install tensorrt" }],
    intermediates: ["onnx"],
    platformLock: "linux_windows",
    requiresGpu: true,
    precisionModes: ["fp16", "fp32", "int8"],
    defaultPrecision: "fp16",
    calibrationRecommendedFor: ["int8"],
    oneWay: true,
    lossy: true,
    notes: "TensorRT engine. NVIDIA GPU required. One-way, platform-locked at runtime.",
    unsupportedNote: "TensorRT requires an NVIDIA GPU. NVIDIA does not support macOS.",
  }),
  route({
    id: "ultralytics.pt.coreml",
    targetFormat: "coreml",
    title: "CoreML",
    displayPath: "model.pt → model.torchscript → model.mlpackage",
    pipDeps: [{ packageName: "coremltools", installHint: "pip install coremltools" }],
    platformLock: "macos_linux",
    intermediates: ["torchscript"],
    precisionModes: ["fp16", "fp32", "int8", "w8a16"],
    defaultPrecision: "fp16",
    calibrationRecommendedFor: [],
    oneWay: true,
    lossy: true,
    notes: "macOS/Linux only. Intermediate TorchScript is discarded. One-way.",
    unsupportedNote: "CoreML export is supported on macOS and Linux. Windows is not supported.",
  }),
  route({
    id: "ultralytics.pt.litert",
    targetFormat: "litert",
    title: "LiteRT",
    displayPath: "model.pt → model.tflite",
    pipDeps: [
      { packageName: "litert-torch>=0.9.0", installHint: 'pip install "ultralytics[export-litert]"' },
      { packageName: "ai-edge-litert>=2.1.4", installHint: 'pip install "ultralytics[export-litert]"' },
    ],
    platformLock: "macos_linux_x86_64",
    precisionModes: ["fp32", "int8", "w8a16", "w8a32"],
    defaultPrecision: "fp32",
    calibrationRecommendedFor: ["int8", "w8a16"],
    oneWay: true,
    lossy: true,
    notes: "CPU-only export for mobile, edge, browser, and Node.js.",
    unsupportedNote: "LiteRT export is supported on macOS and Linux x86-64. Windows and Linux ARM64 are not supported.",
  }),
  route({
    id: "ultralytics.pt.saved_model",
    targetFormat: "saved_model",
    title: "TF SavedModel",
    displayPath: "model.pt → model.onnx → model_saved_model/",
    pipDeps: [
      { packageName: "tensorflow", installHint: "pip install tensorflow" },
      { packageName: "onnx2tf", installHint: "pip install onnx2tf" },
      { packageName: "onnx", installHint: "pip install onnx" },
      { packageName: "onnxruntime", installHint: "pip install onnxruntime" },
    ],
    intermediates: ["onnx"],
    precisionModes: ["fp32", "int8"],
    defaultPrecision: "fp32",
    calibrationRecommendedFor: ["int8"],
    notes: "TensorFlow Serving and cloud deployment. Multi-step pipeline via ONNX.",
  }),
  route({
    id: "ultralytics.pt.pb",
    targetFormat: "pb",
    title: "TF GraphDef",
    displayPath: "model.pt → model.onnx → saved_model/ → model.pb",
    pipDeps: [
      { packageName: "tensorflow", installHint: "pip install tensorflow" },
      { packageName: "onnx2tf", installHint: "pip install onnx2tf" },
      { packageName: "onnx", installHint: "pip install onnx" },
      { packageName: "onnxruntime", installHint: "pip install onnxruntime" },
    ],
    intermediates: ["onnx", "saved_model"],
    notes: "TensorFlow frozen graph for inference. Goes through SavedModel.",
  }),
  route({
    id: "ultralytics.pt.edgetpu",
    targetFormat: "edgetpu",
    title: "TF Edge TPU",
    displayPath: "model.pt → model.onnx → saved_model/ → model.tflite → edgetpu_compiler → model_edgetpu.tflite",
    pipDeps: [
      { packageName: "tensorflow", installHint: "pip install tensorflow" },
      { packageName: "onnx2tf", installHint: "pip install onnx2tf" },
      { packageName: "onnx", installHint: "pip install onnx" },
      { packageName: "onnxruntime", installHint: "pip install onnxruntime" },
    ],
    sysDeps: [{ binaryName: "edgetpu_compiler", installHint: "coral.ai/docs/edgetpu/compiler" }],
    platformLock: "linux_x86_64",
    intermediates: ["onnx", "saved_model", "tflite"],
    precisionModes: ["int8"],
    defaultPrecision: "int8",
    oneWay: true,
    lossy: true,
    notes: "Google Coral hardware only. Full-integer quantisation forced. Linux x86_64 and edgetpu_compiler binary required.",
    unsupportedNote: "The Edge TPU compiler is only available on Linux x86-64.",
  }),
  route({
    id: "ultralytics.pt.paddle",
    targetFormat: "paddle",
    title: "PaddlePaddle",
    displayPath: "model.pt → model_paddle_model/",
    pipDeps: [
      { packageName: "paddlepaddle", installHint: "pip install paddlepaddle" },
      { packageName: "x2paddle", installHint: "pip install x2paddle" },
    ],
    notes: "PaddlePaddle via x2paddle jit.trace. Direct PyTorch → Paddle.",
  }),
  route({
    id: "ultralytics.pt.ncnn",
    targetFormat: "ncnn",
    title: "NCNN",
    displayPath: "model.pt → model_ncnn_model/",
    pipDeps: [
      { packageName: "ncnn", installHint: "pip install ncnn" },
      { packageName: "pnnx", installHint: "pip install pnnx" },
    ],
    precisionModes: ["fp16", "fp32"],
    defaultPrecision: "fp16",
    notes: "Lightweight mobile/embedded inference. Requires ncnn and pnnx.",
  }),
  route({
    id: "ultralytics.pt.mnn",
    targetFormat: "mnn",
    title: "MNN",
    displayPath: "model.pt → model.onnx → model.mnn",
    pipDeps: [
      { packageName: "MNN", installHint: "pip install MNN" },
      { packageName: "onnx", installHint: "pip install onnx" },
    ],
    intermediates: ["onnx"],
    precisionModes: ["fp16", "fp32", "int8"],
    defaultPrecision: "fp16",
    calibrationRecommendedFor: [],
    oneWay: true,
    notes: "MNN mobile inference. Intermediate ONNX is discarded. One-way.",
  }),
  route({
    id: "ultralytics.pt.rknn",
    targetFormat: "rknn",
    title: "RKNN",
    displayPath: "model.pt → _rknn_model/{stem}-{chip}.rknn",
    pipDeps: [
      { packageName: "rknn-toolkit2", installHint: "pip install rknn-toolkit2" },
      { packageName: "onnx", installHint: "pip install onnx" },
    ],
    intermediates: ["onnx"],
    platformLock: "linux",
    precisionModes: ["fp16", "int8"],
    defaultPrecision: "fp16",
    calibrationRecommendedFor: ["int8"],
    oneWay: true,
    lossy: true,
    notes: "Rockchip NPU deployment. Requires target chip name (name= option). Lossy: discards FP precision.",
    unsupportedNote: "RKNN Toolkit 2 only runs on Linux.",
  }),
  route({
    id: "ultralytics.pt.imx",
    targetFormat: "imx",
    title: "Sony IMX500",
    displayPath: "model.pt → FXModel → MCT INT8 → model_imx.onnx → imxconv-pt → model_imx_model/",
    pipDeps: [
      { packageName: "model-compression-toolkit", installHint: "pip install model-compression-toolkit" },
      { packageName: "sony-custom-layers", installHint: "pip install sony-custom-layers" },
      { packageName: "imx500-converter", installHint: "pip install imx500-converter" },
    ],
    sysDeps: [
      { binaryName: "imxconv-pt", installHint: "pip install imx500-converter" },
      { binaryName: "java", installHint: "Install Java >= 17: https://adoptium.net/" },
    ],
    platformLock: "linux",
    intermediates: ["onnx"],
    precisionModes: ["int8", "w8a16"],
    defaultPrecision: "int8",
    calibrationRecommendedFor: ["int8", "w8a16"],
    oneWay: true,
    lossy: true,
    notes: "Sony IMX500 AI sensor. Linux only. INT8 quantization forced. Java >= 17 required.",
    unsupportedNote: "The IMX500 converter (imxconv-pt) is only available on Linux.",
  }),
  route({
    id: "ultralytics.pt.axelera",
    targetFormat: "axelera",
    title: "Axelera",
    displayPath: "model.pt → axelera.quantize → axelera.compile → model_axelera_model/",
    pipDeps: [{ packageName: "axelera", installHint: "pip install axelera-devkit" }],
    platformLock: "linux",
    precisionModes: ["int8"],
    defaultPrecision: "int8",
    oneWay: true,
    lossy: true,
    notes: "Axelera Metis AIPU binary. Linux only. INT8 quantization forced. Requires torch >= 2.8.",
    unsupportedNote: "Axelera Metis SDK requires Linux-specific drivers and compilers.",
  }),
  route({
    id: "ultralytics.pt.executorch",
    targetFormat: "executorch",
    title: "ExecuTorch",
    displayPath: "model.pt → model.pte",
    pipDeps: [{ packageName: "executorch", installHint: "pip install executorch" }],
    oneWay: true,
    notes: "PyTorch ExecuTorch on-device inference. Requires torch >= 2.9. One-way.",
  }),
];
